base:
  project: mlops-flight_c5
  random_state: 42
  target_col: Price

data_source:
  s3_source: source_code/flight_c5.csv

load_data:
  raw_dataset_csv: data/raw/flight_c5.csv

split_data:
  train_path: data/processed/train_flight_c5.csv
  test_path: data/processed/test_flight_c5.csv
  test_size: 0.2

estimators:
  RandomForestRegressor:
    params:
      n_estimators: 120
      max_depth: 15

model_dir: models

reports :
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: prediction_service/model/model.joblib






